// <auto-generated> 

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PRA.DevHabit.Data.Migrations.Application
{
    /// <inheritdoc />
    public partial class RenameIsArcvivedToIsArchived : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "IsArcvived",
                schema: "devhabit",
                table: "Habits",
                newName: "IsArchived");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "IsArchived",
                schema: "devhabit",
                table: "Habits",
                newName: "IsArcvived");
        }
    }
}
