// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRA.DevHabit.Data.Context;

#nullable disable

namespace PRA.DevHabit.Data.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260208214225_Add_HabitTags")]
    partial class Add_HabitTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("devhabit")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRA.DevHabit.Data.Entities.Habit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastCompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Habits", "devhabit");
                });

            modelBuilder.Entity("PRA.DevHabit.Data.Entities.HabitTag", b =>
                {
                    b.Property<string>("HabitId")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TagId")
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("HabitId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("HabitTags", "devhabit");
                });

            modelBuilder.Entity("PRA.DevHabit.Data.Entities.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", "devhabit");
                });

            modelBuilder.Entity("PRA.DevHabit.Data.Entities.Habit", b =>
                {
                    b.OwnsOne("PRA.DevHabit.Data.Entities.Frequency", "Frequency", b1 =>
                        {
                            b1.Property<string>("HabitId")
                                .HasColumnType("nvarchar(500)");

                            b1.Property<int>("TimesPerPeriod")
                                .HasColumnType("int");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("HabitId");

                            b1.ToTable("Habits", "devhabit");

                            b1.WithOwner()
                                .HasForeignKey("HabitId");
                        });

                    b.OwnsOne("PRA.DevHabit.Data.Entities.Milestone", "Milestone", b1 =>
                        {
                            b1.Property<string>("HabitId")
                                .HasColumnType("nvarchar(500)");

                            b1.Property<int>("Current")
                                .HasColumnType("int");

                            b1.Property<int>("Target")
                                .HasColumnType("int");

                            b1.HasKey("HabitId");

                            b1.ToTable("Habits", "devhabit");

                            b1.WithOwner()
                                .HasForeignKey("HabitId");
                        });

                    b.OwnsOne("PRA.DevHabit.Data.Entities.Target", "Target", b1 =>
                        {
                            b1.Property<string>("HabitId")
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("HabitId");

                            b1.ToTable("Habits", "devhabit");

                            b1.WithOwner()
                                .HasForeignKey("HabitId");
                        });

                    b.Navigation("Frequency")
                        .IsRequired();

                    b.Navigation("Milestone");

                    b.Navigation("Target")
                        .IsRequired();
                });

            modelBuilder.Entity("PRA.DevHabit.Data.Entities.HabitTag", b =>
                {
                    b.HasOne("PRA.DevHabit.Data.Entities.Habit", null)
                        .WithMany("HabitTags")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRA.DevHabit.Data.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PRA.DevHabit.Data.Entities.Habit", b =>
                {
                    b.Navigation("HabitTags");
                });
#pragma warning restore 612, 618
        }
    }
}
